### ISSUE TITLE
Shorter report ranges throw error for small set of data

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/graphs#49]
In a fresh host based on ISO RC2 with about of 1hr of data.

When I choose:
- 1 year - it shows data
- 1 month - it shows data
- 1 week - it shows data
- 3 days - it throws "No data found for this time range."
- 1 day - it throws "No data found for this time range."

I would expect to have this data visible in shorter ranges too as the true data is there Even more true than for longer periods due to averaging, don't it?

**Comment by apertome** [comment]
This is probably because the number of summary ipoints for 3 days/1 day is either 0 or 1 -- not enough to draw a line. WE might be able to make it draw a dot if there's only one point. Thinking about this some more.

**Comment by szymontrocha** [comment]
But isn't it opposite - the longer range is the less points? So for 1 day it should be more points to draw than for 1 year...

**Comment by apertome** [comment]
OK, that is odd -- I read it wrong.

**Comment by apertome** [comment]
@szymontrocha are you still seeing this?

**Comment by szymontrocha** [comment]
I'm not able to confirm or deny as I had to reinstall my test host and now it's affected by perfsonar/toolkit#178 so I wasn't able to configure tests.

**Comment by apertome** [comment]
@szymontrocha Andy fixed that issue earlier this week, and I pushed new toolkit RPMs to nightly yesterday, so if you yum update, theoretically it should work now :)

**Comment by arlake228** [comment]
Actually the fix was in libperfsonar which hasn;t been rebuilt. Just
started a build so should be in nightly about 45 minutes after this post.
I’ll also be putting it in staging later today.



On January 20, 2017 at 9:17:39 AM, Michael Johnson (notifications@github.com)
wrote:

@szymontrocha <https://github.com/szymontrocha> Andy fixed that issue
earlier this week, and I pushed new toolkit RPMs to nightly yesterday, so
if you yum update, theoretically it should work now :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/graphs/issues/49#issuecomment-274081964>, or mute
the thread

**Comment by apertome** [comment]
Thanks, @arlake228 -- good catch, I thought it was part of Toolkit.

**Comment by apertome** [comment]
Fixed
