### ISSUE TITLE
Throughput values doubling on certain graphs (3.5 to 4.0 Upgraded)

### ISSUE THREAD

**Issue by schevali** [perfsonar/graphs#78]
Spoke with Andy about an issue with the 3.5 hosts (149.165.239.231 and .243) in the small nodes mesh duplicating values for the graphs on throughput tests during testing and it was determined to be a 3.5-specific bug.

This behavior continues periodically on those same nodes after upgrading to 4.0.

Example between .231 and .237
http://149.165.239.226/maddash-webui/details.cgi?uri=/maddash/grids/INIU+pS+4.0+TEST+Mesh+-+Throughput+iperf3+-+4+hours/149.165.239.237/149.165.239.231/Throughput+Alternate+MA 

And another example between .243 and .239
http://149.165.239.226/maddash-webui/details.cgi?uri=/maddash/grids/INIU+pS+4.0+TEST+Mesh+-+Throughput+iperf3+-+4+hours/149.165.239.243/149.165.239.239/Throughput

The nodes in question auto-updated after release, both are still built upon CentOS 6.

**Comment by apertome** [comment]
I believe this is not really a graphs issue, it's a pScheduler backwards compatibility issue? Or maybe a MeshConfig issue? I guess we should move it to the relevant project.

@arlake228 is this something you plan on handling, or should I plan on looking at this as well?

**Comment by arlake228** [comment]
Looking at what Scott shared and going through the small node dashboard, the only nodes displaying this behavior are still the 3.5 nodes. In both the example shared above, and all the ones I can find in the dashboard, it is the case that the 3.5 host is the one registering the data. You can tell this because the measurement-agent is either .231 or .243, both the 3.5 nodes. I also have a note out to the contact at NIH that was seeing this behavior. If it is just a 3.5 issue, I am not particularly compelled to go back and update regular-testing with a fix.

**Comment by arlake228** [comment]
Turns out those 3.5 hosts are actually labelled incorrectly, they are indeed 4.0 hosts.

**Comment by arlake228** [comment]
Now that I know the hosts are 4.0, I was able to query pscheduler and see that it had three archiver definitions all trying to write to the same archiver. If the timing is write they trigger a race condition in esmond that leads to double values. This is a known issue with esmond and the fix make writes much more expensive, so the decision has been to try to avoid client misconfigurations like these.

The three archiver definitions were the result of the following:

1. The definition at the <test> level in meshconfig-agent-tasks.conf that should have been there
2. A manual definition at the top level of meshconfig-agent-tasks.conf that should not have been there
3. An  auto-generated definition at the top level that was put there by an old version of the meshconfig and not properly cleared out by the new. 

I have fixed the bug per the commit that references this issue so that those old definitions get cleared out. I also removed the manual definitions from the file. If anyone encounters this before the fix, manually removing any manual definitoon and/or old auto-generated definitions will fix this.
